pipeline_manager: Fix rustdoc errors.
Fixes the following:

```
error: unclosed HTML tag `host`
   --> crates/pipeline_manager/src/config.rs:103:53
    |
103 |     /// Accepted values are "sqlite" or "postgres://<host>:<port>".
    |                                                     ^^^^^^
    |
    = note: `-D rustdoc::invalid-html-tags` implied by `-D warnings`

error: unclosed HTML tag `port`
   --> crates/pipeline_manager/src/config.rs:103:60
    |
103 |     /// Accepted values are "sqlite" or "postgres://<host>:<port>".
    |                                                            ^^^^^^
```

Signed-off-by: Ben Pfaff <bpfaff@vmware.com>
CC: Lalith Suresh <lsuresh@vmware.com>
Fixes: 07aa2136b26f ("Add Postgres support")